---
# tasks file for ansible-osx_defaults

###############################################################################
# Terminal                                                                    #
###############################################################################

- name: Close shell on exit
  community.general.osx_defaults:
    domain: com.apple.Terminal
    key: Window Settings.Basic.shellExitAction
    type: int
    value: "1"

###############################################################################
# General UI/UX                                                               #
###############################################################################

- name: Darkmode
  community.general.osx_defaults:
    domain: Apple Global Domain
    key: AppleInterfaceStyle
    type: string
    value: Dark

- name: Use light mode for Microsoft Word
  community.general.osx_defaults:
    domain: com.microsoft.Word
    key: NSRequiresAquaSystemAppearance
    type: bool
    value: "true"

- name: Dock on the left side
  community.general.osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: left

- name: Automatically hide and show the Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: "true"

- name: Remove the auto-hiding Dock delay
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: "0"

- name: Remove the animation when hiding/showing the Dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: autohide-time-modifier
    type: float
    value: "0"

- name: Disable smart quotes as they’re annoying when typing code
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticQuoteSubstitutionEnabled
    type: bool
    value: "false"

- name: Disable smart dashes as they’re annoying when typing code
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticDashSubstitutionEnabled
    type: bool
    value: "false"

###############################################################################
# Screen                                                                      #
###############################################################################

# - name: Save screenshots to Downloads folder.
#   community.general.osx_defaults:
#     domain: com.apple.screencapture
#     key: location
#     type: string
#     value: ${HOME}/Downloads

- name: Require password after screen saver begins
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPassword
    type: int
    value: "1"

- name: Require password immediately after sleep or screen saver begins
  community.general.osx_defaults:
    domain: com.apple.screensaver
    key: askForPasswordDelay
    type: int
    value: "0"

###############################################################################
# Finder                                                                      #
###############################################################################

- name: Expand save panel by default
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: "true"

- name: Avoid creating .DS_Store files on network volumes
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: "true"

- name: Show icons for external hard drives on the desktop
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    type: bool
    value: "true"

- name: Do not show icons for internal hard drives on the desktop
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    type: bool
    value: "false"

- name: Show icons for servers on the desktop
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    type: bool
    value: "true"

- name: Show icons for removable media on the desktop
  community.general.osx_defaults:
    domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    type: bool
    value: "true"

###############################################################################
# Mail                                                                        #
###############################################################################

# seems deprecated
# - name: Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>` in Mail.app
#   community.general.osx_defaults:
#     domain: com.apple.mail
#     key: AddressesIncludeNameOnPasteboard
#     type: bool
#     value: "false"

###############################################################################
# Safari & WebKit                                                             #
###############################################################################

- name: Enable the Develop menu and the Web Inspector in Safari
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: "{{ item }}"
    type: bool
    value: "true"
  loop:
    - IncludeDevelopMenu
    - WebKitDeveloperExtrasEnabledPreferenceKey
    - com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled

- name: Add a context menu item for showing the Web Inspector in web views
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: WebKitDeveloperExtras
    type: bool
    value: "true"
