---
# tasks file for ansible-osx_defaults

- name: darkmode
  osx_defaults:
    domain: "Apple Global Domain"
    key: "AppleInterfaceStyle"
    type: string
    value: "Dark"

- name: Avoid creating .DS_Store files on network volumes
  osx_defaults:
    domain: "com.apple.desktopservices"
    key: "DSDontWriteNetworkStores"
    type: bool
    value: "true"

- name: Show icons for external hard drives on the desktop
  osx_defaults:
    domain: "com.apple.finder"
    key: "ShowExternalHardDrivesOnDesktop"
    type: bool
    value: "true"

- name: Do not show icons for internal hard drives on the desktop
  osx_defaults:
    domain: "com.apple.finder"
    key: "ShowHardDrivesOnDesktop"
    type: bool
    value: "false"

- name: Show icons for servers on the desktop
  osx_defaults:
    domain: "com.apple.finder"
    key: "ShowMountedServersOnDesktop"
    type: bool
    value: "true"

- name: Show icons for removable media on the desktop
  osx_defaults:
    domain: "com.apple.finder"
    key: "ShowRemovableMediaOnDesktop"
    type: bool
    value: "true"

- name: Disable smart quotes as they’re annoying when typing code
  osx_defaults:
    domain: "NSGlobalDomain"
    key: "NSAutomaticQuoteSubstitutionEnabled"
    type: bool
    value: "false"

- name: Disable smart dashes as they’re annoying when typing code
  osx_defaults:
    domain: "NSGlobalDomain"
    key: "NSAutomaticDashSubstitutionEnabled"
    type: bool
    value: "false"

- name: Require password after screen saver begins
  osx_defaults:
    domain: "com.apple.screensaver"
    key: "askForPassword"
    type: int
    value: "1"

- name: Require password immediately after sleep or screen saver begins
  osx_defaults:
    domain: "com.apple.screensaver"
    key: "askForPasswordDelay"
    type: int
    value: "0"

