---
# tasks file for ansible-osx_defaults

- name: darkmode
  osx_defaults:
    domain: "Apple Global Domain"
    key: "AppleInterfaceStyle"
    type: string
    value: "Dark"

- name: Avoid creating .DS_Store files on network volumes
  osx_defaults:
    domain: "com.apple.desktopservices"
    key: "DSDontWriteNetworkStores"
    type: bool
    value: "true"

